from enum import Enum


class AlternativeStatus(Enum):
    ALTERNATIVE_STATUS_UNSPECIFIED = "ALTERNATIVE_STATUS_UNSPECIFIED"
    ALTERNATIVE_STATUS_PARTIAL = "ALTERNATIVE_STATUS_PARTIAL"
    ALTERNATIVE_STATUS_TRUNCATED_FINAL = "ALTERNATIVE_STATUS_TRUNCATED_FINAL"
    ALTERNATIVE_STATUS_FINAL = "ALTERNATIVE_STATUS_FINAL"
